Client/IdentityServer.Web/Controllers/ProductController.cs
using IdentityServer.Web.ApiServices.Interfaces;
using IdentityServer.Web.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace IdentityServer.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly IProductsWebService _productsWebService;
        public ProductController(ILogger<ProductController> logger, IProductsWebService productsWebService)
        {
            _logger = logger;
            _productsWebService = productsWebService;
        }
        // GET: ProductController
        public async Task<ActionResult> Index()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            List<ProductDto> list = new List<ProductDto>();
            var resp = await _productsWebService.GetActiveProductsAsync<ResponseDto>(accessToken);
            if (resp != null && resp.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(resp.Result));
            }
            return View(list);
        }

        // GET: ProductController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            return View();
        }

        // GET: ProductController/Create
        public async Task<ActionResult> Create()
        {
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductDto model)
        {
            try
            {
                var accessToken = await HttpContext.GetTokenAsync("access_token");
                var resp = await _productsWebService.UpdateProductAsync<ResponseDto>(model, accessToken);
                if (resp != null && resp.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }

        }

        // GET: ProductController/Edit/5
        public async Task<ActionResult> Edit(long id)
        {
            ProductDto model = new ProductDto();
            try
            {
                var accessToken = await HttpContext.GetTokenAsync("access_token");
                var resp = await _productsWebService.GetProductByIdAsync<ResponseDto>(id, accessToken);
                if (resp != null && resp.IsSuccess)
                {
                    model = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(resp.Result));
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductDto model)
        {
            try
            {
                var accessToken = await HttpContext.GetTokenAsync("access_token");
                var resp = await _productsWebService.UpdateProductAsync<ResponseDto>(model, accessToken);
                if (resp != null && resp.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }

        }
        [Authorize(Roles = "Administrator")]

        // GET: ProductController/Delete/5
        public async Task<ActionResult> Delete(long id)
        {
            ProductDto model = new ProductDto();
            try
            {
                var accessToken = await HttpContext.GetTokenAsync("access_token");
                var resp = await _productsWebService.GetProductByIdAsync<ResponseDto>(id, accessToken);
                if (resp != null && resp.IsSuccess)
                {
                    model = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(resp.Result));
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }
        [Authorize(Roles = "Administrator")]
        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(ProductDto productDto)
        {
            try
            {
                var accessToken = await HttpContext.GetTokenAsync("access_token");
                var resp = await _productsWebService.DeleteProductAsync<ResponseDto>(productDto.ID, accessToken);
                if (resp != null && resp.IsSuccess)
                {
                    TempData["ListMessage"] = "Data deleted.";
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Client/IdentityServer.Web/Controllers/SecureProductController.cs
using IdentityServer.Web.ApiServices.Interfaces;
using IdentityServer.Web.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace IdentityServer.Web.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class SecureProductController : Controller
    {
        private readonly ILogger<SecureProductController> _logger;
        private readonly IProductsWebService _productsWebService;
        public SecureProductController(ILogger<SecureProductController> logger, IProductsWebService productsWebService)
        {
            _logger = logger;
            _productsWebService = productsWebService;
        }
        // GET: ProductController
        public async Task<ActionResult> Index()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            List<ProductDto> list = new List<ProductDto>();
            var resp = await _productsWebService.GetActiveProductsAsync<ResponseDto>(accessToken);
            if (resp != null && resp.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(resp.Result));
            }
            return View(list);
        }

        // GET: ProductController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            return View();
        }

        // GET: ProductController/Create
        public async Task<ActionResult> Create()
        {
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductDto model)
        {
            try
            {
                var accessToken = await HttpContext.GetTokenAsync("access_token");
                var resp = await _productsWebService.UpdateProductAsync<ResponseDto>(model, accessToken);
                if (resp != null && resp.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }

        }

        // GET: ProductController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            ProductDto model = new ProductDto();
            try
            {
                var accessToken = await HttpContext.GetTokenAsync("access_token");
                var resp = await _productsWebService.GetProductByIdAsync<ResponseDto>(id, accessToken);
                if (resp != null && resp.IsSuccess)
                {
                    model = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(resp.Result));
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductDto model)
        {
            try
            {
                var accessToken = await HttpContext.GetTokenAsync("access_token");
                var resp = await _productsWebService.UpdateProductAsync<ResponseDto>(model, accessToken);
                if (resp != null && resp.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }

        }


        // GET: ProductController/Delete/5
        public async Task<ActionResult> Delete(long id)
        {
            ProductDto model = new ProductDto();
            try
            {
                var accessToken = await HttpContext.GetTokenAsync("access_token");
                var resp = await _productsWebService.GetProductByIdAsync<ResponseDto>(id, accessToken);
                if (resp != null && resp.IsSuccess)
                {
                    model = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(resp.Result));
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(ProductDto productDto)
        {
            try
            {
                var accessToken = await HttpContext.GetTokenAsync("access_token");
                var resp = await _productsWebService.DeleteProductAsync<ResponseDto>(productDto.ID, accessToken);
                if (resp != null && resp.IsSuccess)
                {
                    TempData["ListMessage"] = "Data deleted.";
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Client/IdentityServer.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityServer.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IdentityServer.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SecureProduct" asp-action="Index">Secure Product</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-secondary" asp-area="" asp-controller="Home" asp-action="Index">Hello @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="Index">@User.Claims.Where(a => a.Type == "given_name")?.FirstOrDefault()?.Value</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="Index">@User.Claims.Where(a => a.Type == "sub")?.FirstOrDefault()?.Value</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CallLogin">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">


            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Client/IdentityServer.Web/Views/Shared/json.cshtml
<pre>@ViewBag.Json</pre>